//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanStoreBE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public string CusPhone { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public string CusPassword { get; set; }
        public string CusSurname { get; set; }
        [StringLength(20, ErrorMessage = "Số kí tự không được vượt quá 20")]
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public string CusName { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public string CusEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
