//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanStoreBE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [StringLength(30, ErrorMessage = "Số kí tự không được vượt quá 30")]
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public string Username { get; set; }
        [StringLength(60, ErrorMessage = "Số kí tự không được vượt quá 60")]
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public string Password { get; set; }
        [StringLength(40, ErrorMessage = "Số kí tự không được vượt quá 40")]
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public string Role { get; set; }
    }
}
